spring.datasource:
  url: jdbc:postgresql://localhost:5432/mydatabase
  username: myuser
  password: mypassword
spring.jpa:
  hibernate.ddl-auto: create
  defer-datasource-initialization: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      platform=org:
#        hibernate:
#          PostgreSQLDialect: